all:
	pdflatex presentation.tex
#	bibtex projeto
	pdflatex presentation.tex
	pdflatex presentation.tex
	evince presentation.pdf

clean:
	rm -rf *.aux  *.nav *.log  *.out  *.snm  *.toc *.pdf *.bbl *.blg *.brf *.dvi *.idx *.lof *.lot *.ps

